#!/bin/bash

set -e

# Define a variable for the target user's home directory
TARGET_HOME="/home/${SUDO_USER:-$USER}/"

# Copy the bf20_mill_sims directory to the target directory
	# Create the truetype directory if it doesn't exist
sudo -u ${SUDO_USER:-$USER} mkdir -p "${TARGET_HOME}linuxcnc/configs"
sudo -u ${SUDO_USER:-$USER} cp -r /usr/lib/python3/dist-packages/config/bf20_mill/ "${TARGET_HOME}linuxcnc/configs/"
